## ASSIGNMENT

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
list_

['1', '2', '3', '4', '5']

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

In [6]:
d={}
for i in range(len(list_)):
    d[i]=type(list_[i])

d  

{0: str, 1: str, 2: str, 3: str, 4: str}

In [7]:
d={}
for i in range(len(array_list)):
    d[i]=type(array_list[i])

d 

{0: numpy.str_, 1: numpy.str_, 2: numpy.str_, 3: numpy.str_, 4: numpy.str_}

yes

In [8]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [9]:
type(array_list)

numpy.ndarray

In [10]:
d={}
for i in range(len(array_list)):
    d[i]=type(array_list[i])

d

{0: numpy.int64,
 1: numpy.int64,
 2: numpy.int64,
 3: numpy.int64,
 4: numpy.int64}

In [11]:
d={}
for i in range(len(list_)):
    d[i]=type(list_[i])

d 

{0: str, 1: str, 2: str, 3: str, 4: str}

In [12]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [13]:
np.shape(num_array)

(2, 3)

In [14]:
np.size(num_array)

6

In [15]:
zero_array=np.zeros((3,3))

In [16]:
np.shape(zero_array)

(3, 3)

In [17]:
zero_array


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
import numpy.matlib as nm

In [19]:
identity_matrix=nm.eye(5,5)

In [20]:
type(identity_matrix)

numpy.matrix

In [21]:
identity_matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

----